name: farmers
on: [push]
jobs:
  run:
    runs-on: [ubuntu-latest]
    # optionally use a convenient Ubuntu LTS + DVC + CML image
    container: docker://ghcr.io/iterative/cml:0-dvc2-base1
    steps:
      - uses: actions/checkout@v2
      # may need to setup NodeJS & Python3 on e.g. self-hosted
      # - uses: actions/setup-node@v2
      #   with:
      #     node-version: '16'
      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - uses: iterative/setup-cml@v1
      - uses: iterative/setup-dvc@v1

      - name: cml_run
        env:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
        run: |
          python3 -m venv tutorial-env
          source tutorial-env/bin/activate
          pip3 install -r requirements.txt
          dvc repro

          git fetch --prune
          dvc metrics diff --show-md main > report.md

          # Add Visualization
          echo '## Validating results by region'
          cml publish by_region.png --md >> report.md
          cml send-comment report.md
